### PR TITLE
Refactor file management

### PR DESCRIPTION
**Pull request by ScatteredDrifter**
refactored the YamlCreation file found in yolo/ directory at first. 
Was split up and merged to:
- moduleFileManagement -> gatherFolderPath, gatherFilePath are now contained 
-moduleYamlManagement -> createYaml refactored 

added type annotations and docstrings. 
improved return types and removed sentinel values as mentioned in #30 
- instead the Optional[] return types are now used.

### CODE REVIEW

**Review by FredericLala — CHANGES_REQUESTED** [review]
- the custom error message is gone, when i pick the custom model option and dont provide the necessary .pt file.
grafik

-  the custom error message is gone, when I want to train my custom model in Offline Data, when the necessary data has not been provided.
grafik

- the same error happens when data has been provided
grafik
-> it seems that no yaml file is created

**Comment by ScatteredDrifter** [comment]
Most of those issues are due to the structure of the yolov8-detection.py File which was refactored in a later branch #40 . 
I have merged this branch into the said branch and added a new commit 1d693bb that should solve your issues. 
Because it is referenced in my PR #40 I would endorse answering there and merging this branch as it has been included in the other one as well.

**Comment by ScatteredDrifter** [comment]
I've referenced the wrong commit. The change has been included in the following: 
3af6c42b6893e5ef53a636ad2322c029bbf7ac8e

**Comment by ScatteredDrifter** [comment]
@FredericLala could you please review once more ? Given the information that I've changed or adapted most of those issues in another PR (#40) we could merge this one by now, no?

**Pull request merged**
