### PR TITLE
Establish base structure | refactor Yolov8

### PR DESCRIPTION
**Pull request by ScatteredDrifter**
If made several huge changes to our repository in this branch: 
- merged every file that was loose in the repo to be positioned accordingly as described in docs/CodingConventions.md
- refactored yolov8 detection and split it into several files: moduleYolov8.py, uiYolo.py, uiRunVideo.py
- separated Yolov8-module UI generation and logic  into aboves files 
- removed and rewrote some code smells 
- added flags necessary for further improvements 
- added two sample videos for correct functionality of UI

I ran it locally multiple times during development and encountered no errors after reaching the final state.

### CODE REVIEW

**Review by FredericLala — CHANGES_REQUESTED** [review]
great work, just a few small things:
- Picking the YOLOv8l option gives me your costum error message, but also a
"FileNotFoundError: 'None' does not exist" and then nothing happens.
- In 'moduleYamlManagement.py' you raise an exception when you try to create the yaml. Would a st.error not be more fitting? Because I was not sure if this was an intended error message or a fault in the code. But this is highly subjective.
- Using YOlO detection on an image only shows the image after object detection, there is blank space now where the image before detection used to be

**Comment by ScatteredDrifter** [comment]
regarding your concern of raising an st.error instead --> This exception is at the base layer, arising from the filemanagement module which is not involved with streamlit at all. We could detect such issue by checking for a None-Return type which indicates an issue or we could also pipe the exception as return Option. 
Otherwise I would strongly endorse not combining streamlit with any "backend" if not necessary

**Comment by ScatteredDrifter** [comment]
> Using YOlO detection on an image only shows the image after object detection, there is blank space now, where the image before detection used to be 

I cant reproduce your error, for me it works with both the sample images and custom images 
image

**Comment by ScatteredDrifter** [comment]
adjusted your mentioned issue with downloading new models and also solved #42 on the go. 
- maybe you could give me some further information about this problem: I cannot reproduce it 

@FredericLala 
> Using YOlO detection on an image only shows the image after object detection, there is blank space now, where the image before detection used to be

**Comment by FredericLala** [comment]
grafik
This only seems to happen, when the input source is set to sample data.
But I could not seem to find the error, so maybe it is only on my device.

**Comment by FredericLala** [comment]
> regarding your concern of raising an st.error instead --> This exception is at the base layer, arising from the filemanagement module which is not involved with streamlit at all. We could detect such issue by checking for a None-Return type which indicates an issue or we could also pipe the exception as return Option. Otherwise I would strongly endorse not combining streamlit with any "backend" if not necessary

You are definitely correct here.

**Review by FredericLala — APPROVED** [review]
My core issue of the model loading not working properly is fixed. So this is more than fine 😸

**Comment by ScatteredDrifter** [comment]
> grafik This only seems to happen, when the input source is set to sample data. But I could not seem to find the error, so maybe it is only on my device. I also don't think, that this is really much of a problem, it's just something I found odd.

maybe the others could give some insight on this issue? Does it happen for @SimonCashew @nicolasseng ?

**Pull request merged**
