### PR TITLE
added images from COCO dataset 2014

### PR DESCRIPTION
**Pull request by ScatteredDrifter**
removed large images from sample images and instead added a total of 18 new images from the COCO dataset 
from there. https://cocodataset.org/#home

I've downloaded the 2014 pack and took some images from there

aims to solve #54

### CODE REVIEW

**Review by FredericLala — CHANGES_REQUESTED** [review]
these pictures make more sense than the old ones, as they display a wider range of objects these models can detect. 
when i tried to run the ssd model I got this error:
grafik

It could be that this is obsolete after the refactoring you have done, but I still wanted to mention it

**Comment by ScatteredDrifter** [comment]
> these pictures make more sense than the old ones, as they display a wider range of objects these models can detect. when i tried to run the ssd model I got this error: grafik
> 
> It could be that this is obsolete after the refactoring you have done, but I still wanted to mention it

Yes! This is because the **SSD-Implementation** defaulted to a specific image whenever none was selected yet. It was hardcoded into the structure and thus could not find the image after we've removed or renamed those.

**Comment by ScatteredDrifter** [comment]
@FredericLala I've updated this Branch with the current main-branch. IT should resolve above issue ^

**Review by FredericLala — APPROVED** [review]
works now, thank you 🛩️

**Pull request merged**
