### PR TITLE
added ability to take a picture with your webcam

### PR DESCRIPTION
**Pull request by St4uub**
added ability to take a picture with webcam
#24  done

### CODE REVIEW

**Review by ScatteredDrifter — COMMENTED** [review]
thank you for your contribution. 
I've run it locally and did not notice any undefined behavior so far.
However I would like to make an suggestion or ask about your opinion: 

We could add the option to save this image locally - to access them at a later point again for example - by simply saving the taken screenshot as file in our system. Would that be useful?

**Comment by ScatteredDrifter** [comment]
Could you also provide a description of what you've changed ^^?

**Review by FredericLala — COMMENTED** [review]
Tested it locally and everything works fine, so good job. 👍 
But please do provide a description for this PR, where you also link to the issue you worked on. Then I will approve it.

**Comment by ScatteredDrifter** [comment]
Great Work, thanks !

**Review by FredericLala — APPROVED** [review]

**Review by ScatteredDrifter — CHANGES_REQUESTED** [review]

**Comment by ScatteredDrifter** [comment]
I've solved the issue of an error evoking whenever one selects **video** as source. There the selection of a source - either sample vid or uploaded  vid - was not available. See my change for the source of this issue.

**Review by ScatteredDrifter — APPROVED** [review]

**Pull request merged**
