### PR TITLE
New file for the python dependencies

### PR DESCRIPTION
**Pull request by nicolasseng**
Created a new file for the python dependencies. Tested with a new Conda environment and ``pip install -r requirements.txt`` -> got no errors and ``streamlit run Main.py`` works perfectly for me.

### CODE REVIEW

**Comment by Shengye-Wu** [comment]
I tested this branch with a Mac-Os laptop where no dependencies was installed, it worked out perfectly.

**Review by Shengye-Wu — APPROVED** [review]
Worked out perfectly for me

**Review by ScatteredDrifter — CHANGES_REQUESTED** [review]
While your newly added requirements are correct, this branch is based on an older version than our current main branch.

**Comment by ScatteredDrifter** [comment]
I've updated this branch by merging the current main-branch. Further I added a small flag to the 
.gitignore to prevent custom environments from being uploaded. 

I've tested your new dependencies which ran well on my system as well.

**Review by ScatteredDrifter — APPROVED** [review]

**Pull request merged**
